# Generated by Django 5.1.5 on 2025-01-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidyapath_project', '0005_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
