# Generated by Django 5.1.5 on 2025-02-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidyapath_project', '0008_alter_company_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('package', models.DecimalField(decimal_places=2, max_digits=10)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
            ],
        ),
    ]
